[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["widip"]

[project]
name = "widip"
version = "0.1.0"
description = "Widip is an interactive environment for computing with wiring diagrams in modern systems"
dependencies = [
  "discopy>=1.2.1", "pyyaml>=6.0.1", "watchdog>=4.0.1", "nx-yaml==0.4.1",
]

[project.urls]
"Source" = "https://github.com/colltoaction/widip"
