[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]

[project]
name = "widip"
version = "0.0.1"
description = "Widip is an interactive environment for computing with wiring diagrams in modern systems"
dependencies = [
  "discopy>=1.1.7", "pyyaml>=6.0.1", "watchdog>=4.0.1",
]

[project.urls]
"Source" = "https://github.com/colltoaction/widip"
